truncate table Pegasus_Buildings          ;
truncate table Pegasus_Crew               ;
truncate table Pegasus_Equipment          ;
truncate table Pegasus_Maps               ;
truncate table Pegasus_Missions           ;
truncate table Pegasus_New_Stock          ;
truncate table Pegasus_Npcs               ;
truncate table Pegasus_Personal_Resources ;
truncate table Pegasus_Squadrons          ;
truncate table Pegasus_Stock              ;
truncate table Pegasus_Test_Missions      ;
truncate table Pegasus_Test_Npcs          ;
truncate table Pegasus_Test_Stock         ;
truncate table Pegasus_Users              ;
-- truncate table Orion_Buildings            ;
-- truncate table Orion_Crew                 ;
-- truncate table Orion_Equipment            ;
-- truncate table Orion_Maps                 ;
-- truncate table Orion_Missions             ;
-- truncate table Orion_New_Stock            ;
-- truncate table Orion_Npcs                 ;
-- truncate table Orion_Personal_Resources   ;
-- truncate table Orion_Squadrons            ;
-- truncate table Orion_Stock                ;
-- truncate table Orion_Test_Missions        ;
-- truncate table Orion_Test_Npcs            ;
-- truncate table Orion_Test_Stock           ;
-- truncate table Orion_Users                ;
-- truncate table Artemis_Buildings          ;
-- truncate table Artemis_Crew               ;
-- truncate table Artemis_Equipment          ;
-- truncate table Artemis_Maps               ;
-- truncate table Artemis_Missions           ;
-- truncate table Artemis_New_Stock          ;
-- truncate table Artemis_Npcs               ;
-- truncate table Artemis_Personal_Resources ;
-- truncate table Artemis_Squadrons          ;
-- truncate table Artemis_Stock              ;
-- truncate table Artemis_Test_Missions      ;
-- truncate table Artemis_Test_Npcs          ;
-- truncate table Artemis_Test_Stock         ;
-- truncate table Artemis_Users              ;
--insert into Orion_Maps (id, sector, x, y, bg, fg_updated) select id, sector, x, y, image, UTC_TIMESTAMP() from background;
--insert into Artemis_Maps (id, sector, x, y, bg, fg_updated) select id, sector, x, y, image, UTC_TIMESTAMP() from background;
insert into Pegasus_Maps (id, sector, x, y, bg, fg_updated) select id, sector, x, y, image, UTC_TIMESTAMP() from background;
--UPDATE Orion_Maps m JOIN Pardus_Maps p ON m.id = p.id SET m.wormhole = p.wormhole, m.fg='foregrounds/wormhole.png', m.fg_updated = UTC_TIMESTAMP() WHERE p.wormhole is not null;
--UPDATE Artemis_Maps m JOIN Pardus_Maps p ON m.id = p.id SET m.wormhole = p.wormhole, m.fg='foregrounds/wormhole.png', m.fg_updated = UTC_TIMESTAMP() WHERE p.wormhole is not null;
UPDATE Pegasus_Maps m JOIN Pardus_Maps p ON m.id = p.id SET m.wormhole = p.wormhole, m.fg='foregrounds/wormhole.png', m.fg_updated = UTC_TIMESTAMP() WHERE p.wormhole is not null;
--UPDATE Orion_Maps m JOIN Pardus_Sectors s ON m.sector = s.name SET m.cluster = s.c_name;
--UPDATE Artemis_Maps m JOIN Pardus_Sectors s ON m.sector = s.name SET m.cluster = s.c_name;
UPDATE Pegasus_Maps m JOIN Pardus_Sectors s ON m.sector = s.name SET m.cluster = s.c_name;